/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as NovelsRouteImport } from './routes/novels'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NovelSlugRouteImport } from './routes/novel.$slug'
import { Route as NovelSlugNumberRouteImport } from './routes/novel.$slug.$number'
import { Route as ApiAdminUploadRouteImport } from './routes/api/admin/upload'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const NovelsRoute = NovelsRouteImport.update({
  id: '/novels',
  path: '/novels',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NovelSlugRoute = NovelSlugRouteImport.update({
  id: '/novel/$slug',
  path: '/novel/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NovelSlugNumberRoute = NovelSlugNumberRouteImport.update({
  id: '/$number',
  path: '/$number',
  getParentRoute: () => NovelSlugRoute,
} as any)
const ApiAdminUploadRoute = ApiAdminUploadRouteImport.update({
  id: '/api/admin/upload',
  path: '/api/admin/upload',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/novels': typeof NovelsRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/novel/$slug': typeof NovelSlugRouteWithChildren
  '/api/admin/upload': typeof ApiAdminUploadRoute
  '/novel/$slug/$number': typeof NovelSlugNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/novels': typeof NovelsRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/novel/$slug': typeof NovelSlugRouteWithChildren
  '/api/admin/upload': typeof ApiAdminUploadRoute
  '/novel/$slug/$number': typeof NovelSlugNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/novels': typeof NovelsRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/novel/$slug': typeof NovelSlugRouteWithChildren
  '/api/admin/upload': typeof ApiAdminUploadRoute
  '/novel/$slug/$number': typeof NovelSlugNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/library'
    | '/login'
    | '/novels'
    | '/register'
    | '/search'
    | '/novel/$slug'
    | '/api/admin/upload'
    | '/novel/$slug/$number'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/library'
    | '/login'
    | '/novels'
    | '/register'
    | '/search'
    | '/novel/$slug'
    | '/api/admin/upload'
    | '/novel/$slug/$number'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/library'
    | '/login'
    | '/novels'
    | '/register'
    | '/search'
    | '/novel/$slug'
    | '/api/admin/upload'
    | '/novel/$slug/$number'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  NovelsRoute: typeof NovelsRoute
  RegisterRoute: typeof RegisterRoute
  SearchRoute: typeof SearchRoute
  NovelSlugRoute: typeof NovelSlugRouteWithChildren
  ApiAdminUploadRoute: typeof ApiAdminUploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novels': {
      id: '/novels'
      path: '/novels'
      fullPath: '/novels'
      preLoaderRoute: typeof NovelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novel/$slug': {
      id: '/novel/$slug'
      path: '/novel/$slug'
      fullPath: '/novel/$slug'
      preLoaderRoute: typeof NovelSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novel/$slug/$number': {
      id: '/novel/$slug/$number'
      path: '/$number'
      fullPath: '/novel/$slug/$number'
      preLoaderRoute: typeof NovelSlugNumberRouteImport
      parentRoute: typeof NovelSlugRoute
    }
    '/api/admin/upload': {
      id: '/api/admin/upload'
      path: '/api/admin/upload'
      fullPath: '/api/admin/upload'
      preLoaderRoute: typeof ApiAdminUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface NovelSlugRouteChildren {
  NovelSlugNumberRoute: typeof NovelSlugNumberRoute
}

const NovelSlugRouteChildren: NovelSlugRouteChildren = {
  NovelSlugNumberRoute: NovelSlugNumberRoute,
}

const NovelSlugRouteWithChildren = NovelSlugRoute._addFileChildren(
  NovelSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  NovelsRoute: NovelsRoute,
  RegisterRoute: RegisterRoute,
  SearchRoute: SearchRoute,
  NovelSlugRoute: NovelSlugRouteWithChildren,
  ApiAdminUploadRoute: ApiAdminUploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
